# Generated by Django 4.1 on 2023-07-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadia', '0002_customer_order_orderitem_product_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
